// Generated by gencpp from file gnss_comm/GnssBestXYZMsg.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSBESTXYZMSG_H
#define GNSS_COMM_MESSAGE_GNSSBESTXYZMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssBestXYZMsg_
{
  typedef GnssBestXYZMsg_<ContainerAllocator> Type;

  GnssBestXYZMsg_()
    : header()
    , pos()
    , pos_sigma()
    , vel()
    , vel_sigma()
    , num_svs(0)  {
    }
  GnssBestXYZMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)
    , pos_sigma(_alloc)
    , vel(_alloc)
    , vel_sigma(_alloc)
    , num_svs(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pos_type;
  _pos_type pos;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pos_sigma_type;
  _pos_sigma_type pos_sigma;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vel_type;
  _vel_type vel;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vel_sigma_type;
  _vel_sigma_type vel_sigma;

   typedef uint32_t _num_svs_type;
  _num_svs_type num_svs;





  typedef boost::shared_ptr< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> const> ConstPtr;

}; // struct GnssBestXYZMsg_

typedef ::gnss_comm::GnssBestXYZMsg_<std::allocator<void> > GnssBestXYZMsg;

typedef boost::shared_ptr< ::gnss_comm::GnssBestXYZMsg > GnssBestXYZMsgPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssBestXYZMsg const> GnssBestXYZMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos &&
    lhs.pos_sigma == rhs.pos_sigma &&
    lhs.vel == rhs.vel &&
    lhs.vel_sigma == rhs.vel_sigma &&
    lhs.num_svs == rhs.num_svs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8760f15dc1e5a1752bf3a62384ef184e";
  }

  static const char* value(const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8760f15dc1e5a175ULL;
  static const uint64_t static_value2 = 0x2bf3a62384ef184eULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssBestXYZMsg";
  }

  static const char* value(const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] pos\n"
"float64[] pos_sigma\n"
"float64[] vel\n"
"float64[] vel_sigma\n"
"uint32    num_svs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
      stream.next(m.pos_sigma);
      stream.next(m.vel);
      stream.next(m.vel_sigma);
      stream.next(m.num_svs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssBestXYZMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssBestXYZMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "pos_sigma[]" << std::endl;
    for (size_t i = 0; i < v.pos_sigma.size(); ++i)
    {
      s << indent << "  pos_sigma[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos_sigma[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "vel_sigma[]" << std::endl;
    for (size_t i = 0; i < v.vel_sigma.size(); ++i)
    {
      s << indent << "  vel_sigma[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel_sigma[i]);
    }
    s << indent << "num_svs: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_svs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSBESTXYZMSG_H
