(cl:in-package gnss_comm-msg)
(cl:export '(SAT-VAL
          SAT
          TTR-VAL
          TTR
          TOE-VAL
          TOE
          FREQO-VAL
          FREQO
          IODE-VAL
          IODE
          HEALTH-VAL
          HEALTH
          AGE-VAL
          AGE
          URA-VAL
          URA
          POS_X-VAL
          POS_X
          POS_Y-VAL
          POS_Y
          POS_Z-VAL
          POS_Z
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          TAU_N-VAL
          TAU_N
          GAMMA-VAL
          GAMMA
          DELTA_TAU_N-VAL
          DELTA_TAU_N
))