(cl:in-package gnss_comm-msg)
(cl:export '(TIME-VAL
          TIME
          FIX_TYPE-VAL
          FIX_TYPE
          VALID_FIX-VAL
          VALID_FIX
          DIFF_SOLN-VAL
          DIFF_SOLN
          CARR_SOLN-VAL
          CARR_SOLN
          NUM_SV-VAL
          NUM_SV
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEIGHT_MSL-VAL
          HEIGHT_MSL
          H_ACC-VAL
          H_ACC
          V_ACC-VAL
          V_ACC
          P_DOP-VAL
          P_DOP
          VEL_N-VAL
          VEL_N
          VEL_E-VAL
          VEL_E
          VEL_D-VAL
          VEL_D
          VEL_ACC-VAL
          VEL_ACC
))