(cl:in-package gnss_comm-msg)
(cl:export '(SAT-VAL
          SAT
          TTR-VAL
          TTR
          TOE-VAL
          TOE
          TOC-VAL
          TOC
          TOE_TOW-VAL
          TOE_TOW
          WEEK-VAL
          WEEK
          IODE-VAL
          IODE
          IODC-VAL
          IODC
          HEALTH-VAL
          HEALTH
          CODE-VAL
          CODE
          URA-VAL
          URA
          A-VAL
          A
          E-VAL
          E
          I0-VAL
          I0
          OMG-VAL
          OMG
          OMG0-VAL
          OMG0
          M0-VAL
          M0
          DELTA_N-VAL
          DELTA_N
          OMG_DOT-VAL
          OMG_DOT
          I_DOT-VAL
          I_DOT
          CUC-VAL
          CUC
          CUS-VAL
          CUS
          CRC-VAL
          CRC
          CRS-VAL
          CRS
          CIC-VAL
          CIC
          CIS-VAL
          CIS
          AF0-VAL
          AF0
          AF1-VAL
          AF1
          AF2-VAL
          AF2
          TGD0-VAL
          TGD0
          TGD1-VAL
          TGD1
          A_DOT-VAL
          A_DOT
          N_DOT-VAL
          N_DOT
))