# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gnss_comm/GnssTimePulseInfoMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gnss_comm.msg

class GnssTimePulseInfoMsg(genpy.Message):
  _md5sum = "de306035e295e3c4b1e0771a216b495a"
  _type = "gnss_comm/GnssTimePulseInfoMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message contains information of UBX-TIM-TP message. 
# reference: [1]. UBX-18010854-R08, page 156

GnssTimeMsg time    # GNSS time of the next time pulse
bool utc_based      # if the time is UTC (1=UTC, 0=GNSS)
uint32 time_sys     # GNSS time reference system, if the time base is GNSS (utc_base=0)
================================================================================
MSG: gnss_comm/GnssTimeMsg
# This message contains GNSS time expressed in the form of 
# GNSS week number and time of week(in seconds)

uint32 week
float64 tow"""
  __slots__ = ['time','utc_based','time_sys']
  _slot_types = ['gnss_comm/GnssTimeMsg','bool','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,utc_based,time_sys

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GnssTimePulseInfoMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = gnss_comm.msg.GnssTimeMsg()
      if self.utc_based is None:
        self.utc_based = False
      if self.time_sys is None:
        self.time_sys = 0
    else:
      self.time = gnss_comm.msg.GnssTimeMsg()
      self.utc_based = False
      self.time_sys = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IdBI().pack(_x.time.week, _x.time.tow, _x.utc_based, _x.time_sys))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = gnss_comm.msg.GnssTimeMsg()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.time.week, _x.time.tow, _x.utc_based, _x.time_sys,) = _get_struct_IdBI().unpack(str[start:end])
      self.utc_based = bool(self.utc_based)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IdBI().pack(_x.time.week, _x.time.tow, _x.utc_based, _x.time_sys))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = gnss_comm.msg.GnssTimeMsg()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.time.week, _x.time.tow, _x.utc_based, _x.time_sys,) = _get_struct_IdBI().unpack(str[start:end])
      self.utc_based = bool(self.utc_based)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IdBI = None
def _get_struct_IdBI():
    global _struct_IdBI
    if _struct_IdBI is None:
        _struct_IdBI = struct.Struct("<IdBI")
    return _struct_IdBI
